### ISSUE TITLE
SyntaxError: JSON.parse:

### ISSUE THREAD

**Issue by gour** [GothenburgBitFactory/holidata.net#2]
Hello,

after seeing that the data for Croatian holidays are added to the web site, I've tried to update my holidays file, but it reports:

```
Data for hr-HR, for 2020 could not be downloaded.  This could
mean that you do not have an internet connection, or that
Holidata.net does not support this locale and/or year.
```

Then I tried to visit the file online and even for Germany when visiting `https://holidata.net/de-DE/2020.json` I get:

```
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data
```

Any hint?

**Comment by lauft** [comment]
While debugging the run of the `update-holidays.pl` script, I found the following "response":
```
Can't verify SSL peers without knowing which Certificate Authorities to trust

This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
envirionment variable or by installing the Mozilla::CA module.

To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
envirionment variable to 0.  If you do this you can't be sure that you
communicate with the expected peer.
```
Installing `Mozilla::CA` solved the problem then for me...

**Comment by gour** [comment]
> Installing the perl module Mozilla::CA solved the problem then for me...

Thank you for taking time...however, I'm moving away from Taskwarrior (to org-mode) since I do not foresee that 2.6/3.0 is going to be released ever and I do really miss "recurring overhaul" having many recurring events which are not properly handled by tw and then I have to do extra managing of those tasks.

All the best!

**Comment by lauft** [comment]
> ...I'm moving away from Taskwarrior (to org-mode) since I do not foresee that 2.6/3.0 is going to be released ever and I do really miss "recurring overhaul" having many recurring events which are not properly handled by tw and then I have to do extra managing of those tasks.

Sad to see you go, but we will always welcome you back! 😊
